# params for ASM

catboost:
  iterations:          50
  learning_rate:       0.4
  depth:               8
  l2_leaf_reg:         3
  border_count:        128
  bagging_temperature: 0
  task_type:           "CPU"
  verbose:             0
  random_seed:         42

ecg:
  downsampling: (0.25, 0.05)

  timevae:
    epochs : 150 #timevae repo
    nn:
      predictor_lr      : 0.008
      predictor_epochs  : 150
      predictor_dropout : 0.05
      predictor_hidden_sizes : [16, 8] # latent to y output

  ts2vec:
    z_pooling_method   : "mean"
    ts2vec_hidden_dims : 32 # units in each layer (> than latent dim)
    ts2vec_output_dims : 16 # latent dim
    ts2vec_depth       : 4 # num layers
    ts2vec_batch_size  : 32
    ts2vec_epochs      : 20

    predictor_lr       : 0.02
    predictor_epochs   : 300
    predictor_dropout  : 0.05
    predictor_hidden_sizes : [16, 48, 64]

  moment:
    classification:
      predictor_lr      : 0.009
      predictor_epochs  : 100
      predictor_dropout : 0.05
      predictor_hidden_sizes : [2048, 256, 128] # latent to y output


india_catchment:
  downsampling: (0.3, 0.08)
  timevae:
    params : "none"

  ts2vec:
    z_pooling_method   : "mean"
    ts2vec_hidden_dims : 12 # units in each layer (> than latent dim)
    ts2vec_output_dims : 8 # latent dim
    ts2vec_depth       : 2 # num layers
    ts2vec_batch_size  : 32
    ts2vec_epochs      : 20

    predictor_lr       : 0.009
    predictor_epochs   : 150
    predictor_dropout  : 0.05
    predictor_hidden_sizes : [16, 28, 36]

germany_catchment:
  timevae:
    params: "none"

  ts2vec:
    z_pooling_method   : "mean"
    ts2vec_hidden_dims : 3 # units in each layer (> than latent dim)
    ts2vec_output_dims : 2 # latent dim
    ts2vec_depth       : 2 # num layers
    ts2vec_batch_size  : 32
    ts2vec_epochs      : 20

    predictor_lr       : 0.009
    predictor_epochs   : 150
    predictor_dropout  : 0.05
    predictor_hidden_sizes : [3]


china_weather:
  timevae:
    epochs: 300
    nn:
      predictor_lr      : 0.008
      predictor_epochs  : 150
      predictor_dropout : 0.05
      predictor_hidden_sizes : [16, 8] # latent to y output

  ts2vec:
    z_pooling_method   : "mean"
    ts2vec_hidden_dims : 16 # units in each layer (> than latent dim)
    ts2vec_output_dims : 8 # latent dim
    ts2vec_depth       : 2 # num layers
    ts2vec_batch_size  : 32
    ts2vec_epochs      : 20

    predictor_lr       : 0.009
    predictor_epochs   : 150
    predictor_dropout  : 0.05
    predictor_hidden_sizes : [16, 48, 64] # latent to y output

    downsampling: (0.25, 0.05)

  moment:
    model_name         : "MOMENT-1-large"
    task_name          : "embedding" # "classification" or "embedding"
    predictor_lr       : 0.009
    predictor_epochs   : 100
    predictor_dropout  : 0.05
    predictor_hidden_sizes : [256, 64, 16] # latent to y output

weatherbench:
  timevae:
    params: "none"

  ts2vec:
    z_pooling_method   : "mean"
    ts2vec_hidden_dims : 3 # units in each layer (> than latent dim)
    ts2vec_output_dims : 2 # latent dim
    ts2vec_depth       : 2 # num layers
    ts2vec_batch_size  : 32
    ts2vec_epochs      : 20

    predictor_lr       : 0.009
    predictor_epochs   : 150
    predictor_dropout  : 0.05
    predictor_hidden_sizes : [3]


